;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        fiplr-find-file
        kill-region
        rspec-verify-single
        save-some-buffers
        string-inflection-camelcase
        string-inflection-underscore
        xterm-paste
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ag-project
        c-electric-paren
        c-hungry-delete-forward
        electric-pair-delete-pair
        keyboard-escape-quit
        ))
